In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [5]:
df.drop(columns=['Unnamed: 32','id'],inplace=True)

In [6]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [7]:
X_tr, X_ts, y_tr, y_ts = train_test_split(df.iloc[:,1:],df.iloc[:,0], test_size=0.2)

In [8]:
scaler = StandardScaler()
X_tr = scaler.fit_transform(X_tr)
X_ts = scaler.transform(X_ts)

In [9]:
X_tr

array([[ 0.98539142, -1.02383047,  0.95799002, ...,  0.48414076,
        -0.22045066, -0.24733653],
       [ 2.00346398,  0.28339445,  1.9253922 , ...,  1.76759154,
        -0.99809565, -0.51504316],
       [-0.64986959, -1.11942279, -0.58692195, ..., -0.84261091,
        -0.26666317,  1.07548104],
       ...,
       [ 0.16920294,  1.45440032,  0.10784871, ..., -0.07814775,
        -0.27463084, -0.76920189],
       [-0.35857971, -0.71793506, -0.40181729, ..., -0.50103232,
         0.20661667, -0.7729953 ],
       [ 3.02153653,  0.5414937 ,  3.07287357, ...,  2.07132079,
         0.4185568 ,  0.70210074]], shape=(455, 30))

In [10]:
y_tr

29     M
449    M
145    B
319    B
396    B
      ..
179    B
102    B
542    B
195    B
521    M
Name: diagnosis, Length: 455, dtype: object

In [12]:
enc = LabelEncoder()
y_tr = enc.fit_transform(y_tr)
y_ts = enc.transform(y_ts)

In [13]:
y_tr

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1])

**Using Tensors**

In [14]:
X_tr_tensor = torch.from_numpy(X_tr)
X_ts_tensor = torch.from_numpy(X_ts) 
y_tr_tensor = torch.from_numpy(y_tr)
y_ts_tensor = torch.from_numpy(y_ts)

In [16]:
X_tr_tensor.shape

torch.Size([455, 30])

In [17]:
y_tr_tensor.shape

torch.Size([455])

**Model Initialization**

In [20]:
class SimpleNeuralNet():

    def __init__(self, X):
        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias  = torch.zeros(1,dtype=torch.float64, requires_grad=True)

    def forward(self,X):
        z = torch.matmul(X, self.weights) + self.bias
        ypred = torch.sigmoid(z)
        return ypred
    
    def loss_func(self, ypred, y):
        epsilon = 1e-7
        ypred = torch.clamp(ypred, epsilon, 1 - epsilon)

        loss = -(y_tr_tensor * torch.log(ypred) + (1-y_tr_tensor) * torch.log(1 - ypred)).mean()
        return loss

In [46]:
model = SimpleNeuralNet(X_tr_tensor)

learning_rate = 0.1
epochs = 50
for epoch in range(epochs):
    ypred = model.forward(X_tr_tensor)

    loss = model.loss_func(ypred, y_tr_tensor)

    loss.backward()

    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f"Epoch: {epoch + 1},  Loss: {round(loss.item(), 6)}")

Epoch: 1,  Loss: 3.540763
Epoch: 2,  Loss: 3.409426
Epoch: 3,  Loss: 3.276321
Epoch: 4,  Loss: 3.140548
Epoch: 5,  Loss: 3.005742
Epoch: 6,  Loss: 2.870725
Epoch: 7,  Loss: 2.733356
Epoch: 8,  Loss: 2.594184
Epoch: 9,  Loss: 2.447818
Epoch: 10,  Loss: 2.2944
Epoch: 11,  Loss: 2.143305
Epoch: 12,  Loss: 1.997058
Epoch: 13,  Loss: 1.852605
Epoch: 14,  Loss: 1.711099
Epoch: 15,  Loss: 1.571497
Epoch: 16,  Loss: 1.438133
Epoch: 17,  Loss: 1.313532
Epoch: 18,  Loss: 1.203206
Epoch: 19,  Loss: 1.10817
Epoch: 20,  Loss: 1.02876
Epoch: 21,  Loss: 0.964435
Epoch: 22,  Loss: 0.913754
Epoch: 23,  Loss: 0.874582
Epoch: 24,  Loss: 0.844515
Epoch: 25,  Loss: 0.821301
Epoch: 26,  Loss: 0.803095
Epoch: 27,  Loss: 0.788515
Epoch: 28,  Loss: 0.77658
Epoch: 29,  Loss: 0.766611
Epoch: 30,  Loss: 0.758143
Epoch: 31,  Loss: 0.750848
Epoch: 32,  Loss: 0.744495
Epoch: 33,  Loss: 0.738912
Epoch: 34,  Loss: 0.733971
Epoch: 35,  Loss: 0.729571
Epoch: 36,  Loss: 0.72563
Epoch: 37,  Loss: 0.722085
Epoch: 38,  Loss: 0.718882
Epoch: 39,  Loss: 0.715976
Epoch: 40,  Loss: 0.71333
Epoch: 41,  Loss: 0.710913
Epoch: 42,  Loss: 0.7087
Epoch: 43,  Loss: 0.706666
Epoch: 44,  Loss: 0.704792
Epoch: 45,  Loss: 0.703063
Epoch: 46,  Loss: 0.701463
Epoch: 47,  Loss: 0.69998
Epoch: 48,  Loss: 0.698602
Epoch: 49,  Loss: 0.697319
Epoch: 50,  Loss: 0.696124

In [47]:
model.bias

tensor([-0.3056], dtype=torch.float64, requires_grad=True)

In [48]:
with torch.no_grad():
    ypred = model.forward(X_ts_tensor)
    ypred = (ypred > 0.9).float()
    acc = (ypred == y_ts_tensor).float().mean()
    print(f"Accuracy: {acc}")

Accuracy: 0.6292705535888672